version: '3'

services:
  redis:
    image: redis:latest
    command: redis-server --requirepass apm191!! --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
